/* 
 * Brainrex API Explorer
 *
 * Welcome to the Brainrex API explorer, we make analytics tools for crypto and blockchain. Our currently propiertary models offer sentiment analysis, market making, blockchain monitoring and face-id verification. This AI models can be consumed from this API. We also offer integrations to open data and propietary data providers, as well as free test data we collect. There is a collection of data transformation tools. Join our Telegram group to get the latest news and ask questions [https://t.me/brainrex, #brainrex](https://t.me/brainrex). More about Brainrex at [https://brainrex.com](http://brainrex.com). Full Documentation can be found at [https://brainrexapi.github.io/docs](https://brainrexapi.github.io/docs)
 *
 * OpenAPI spec version: 0.1.1
 * Contact: support@brainrex.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


#[allow(unused_imports)]
use serde_json::Value;

#[derive(Debug, Serialize, Deserialize)]
pub struct InlineResponse2002 {
  #[serde(rename = "blockchain")]
  blockchain: Option<String>
}

impl InlineResponse2002 {
  pub fn new() -> InlineResponse2002 {
    InlineResponse2002 {
      blockchain: None
    }
  }

  pub fn set_blockchain(&mut self, blockchain: String) {
    self.blockchain = Some(blockchain);
  }

  pub fn with_blockchain(mut self, blockchain: String) -> InlineResponse2002 {
    self.blockchain = Some(blockchain);
    self
  }

  pub fn blockchain(&self) -> Option<&String> {
    self.blockchain.as_ref()
  }

  pub fn reset_blockchain(&mut self) {
    self.blockchain = None;
  }

}



